### ISSUE TITLE
OSError: CUDA runtime library not found

### ISSUE THREAD

**Issue by andyyuan78** [hannes-brt/hebel#20]
ubgpu@ubgpu:~/github/hebel$ sudo pip install pyCUDA
Requirement already satisfied (use --upgrade to upgrade): pyCUDA in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.2.0 in /usr/local/lib/python2.7/dist-packages (from pyCUDA)
Requirement already satisfied (use --upgrade to upgrade): pytools>=2011.2 in /usr/local/lib/python2.7/dist-packages (from pyCUDA)
Requirement already satisfied (use --upgrade to upgrade): pytest>=2 in /usr/local/lib/python2.7/dist-packages (from pyCUDA)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from pytools>=2011.2->pyCUDA)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from pytools>=2011.2->pyCUDA)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.25 in /usr/local/lib/python2.7/dist-packages (from pytest>=2->pyCUDA)
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ sudo pip install PyCUDA
Requirement already satisfied (use --upgrade to upgrade): PyCUDA in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.2.0 in /usr/local/lib/python2.7/dist-packages (from PyCUDA)
Requirement already satisfied (use --upgrade to upgrade): pytools>=2011.2 in /usr/local/lib/python2.7/dist-packages (from PyCUDA)
Requirement already satisfied (use --upgrade to upgrade): pytest>=2 in /usr/local/lib/python2.7/dist-packages (from PyCUDA)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from pytools>=2011.2->PyCUDA)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from pytools>=2011.2->PyCUDA)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.25 in /usr/local/lib/python2.7/dist-packages (from pytest>=2->PyCUDA)
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ echo $PYTHONPATH
/usr/local/lib/python2.7/dist-packages
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ python train_model.py examples/mnist_neural_net_shallow.yml
Traceback (most recent call last):
  File "train_model.py", line 39, in <module>
    run_from_config(yaml_src)
  File "/home/ubgpu/github/hebel/hebel/config.py", line 41, in run_from_config
    config = load(yaml_src)
  File "/home/ubgpu/github/hebel/hebel/config.py", line 92, in load
    proxy_graph = yaml.load(string, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 90, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/home/ubgpu/github/hebel/hebel/config.py", line 318, in multi_constructor
    mapping = loader.construct_mapping(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 90, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/home/ubgpu/github/hebel/hebel/config.py", line 318, in multi_constructor
    mapping = loader.construct_mapping(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 90, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/home/ubgpu/github/hebel/hebel/config.py", line 323, in multi_constructor
    classname = try_to_import(tag_suffix)
  File "/home/ubgpu/github/hebel/hebel/config.py", line 251, in try_to_import
    exec('import %s' % modulename)
  File "<string>", line 1, in <module>
  File "/home/ubgpu/github/hebel/hebel/layers/__init__.py", line 17, in <module>
    from .dummy_layer import DummyLayer
  File "/home/ubgpu/github/hebel/hebel/layers/dummy_layer.py", line 17, in <module>
    from .hidden_layer import HiddenLayer
  File "/home/ubgpu/github/hebel/hebel/layers/hidden_layer.py", line 25, in <module>
    from ..pycuda_ops import linalg
  File "/home/ubgpu/github/hebel/hebel/pycuda_ops/linalg.py", line 32, in <module>
    from . import cublas
  File "/home/ubgpu/github/hebel/hebel/pycuda_ops/cublas.py", line 47, in <module>
    import cuda
  File "/home/ubgpu/github/hebel/hebel/pycuda_ops/cuda.py", line 35, in <module>
    from cudart import *
  File "/home/ubgpu/github/hebel/hebel/pycuda_ops/cudart.py", line 60, in <module>
    raise OSError('CUDA runtime library not found')
OSError: CUDA runtime library not found

**Comment by hannes-brt** [comment]
Make sure the CUDA SDK is installed and on your LD_LIBRARY_PATH.
