### ISSUE TITLE
AttributeError: python: undefined symbol: cuPointerGetAttribute

### ISSUE THREAD

**Issue by andyyuan78** [hannes-brt/hebel#21]
ubgpu@ubgpu:~/github/hebel$ echo $LD_LIBRARY_PATH
/usr/local/cuda:/usr/local/cuda/bin:/usr/local/cuda/lib64:/home/ubgpu/torch/install/lib:/home/ubgpu/torch/install/lib
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ 
ubgpu@ubgpu:~/github/hebel$ python train_model.py examples/mnist_neural_net_shallow.yml
Traceback (most recent call last):
  File "train_model.py", line 39, in <module>
    run_from_config(yaml_src)
  File "/home/ubgpu/github/hebel/hebel/config.py", line 41, in run_from_config
    config = load(yaml_src)
  File "/home/ubgpu/github/hebel/hebel/config.py", line 92, in load
    proxy_graph = yaml.load(string, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 90, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/home/ubgpu/github/hebel/hebel/config.py", line 318, in multi_constructor
    mapping = loader.construct_mapping(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 90, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/home/ubgpu/github/hebel/hebel/config.py", line 318, in multi_constructor
    mapping = loader.construct_mapping(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 90, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/home/ubgpu/github/hebel/hebel/config.py", line 323, in multi_constructor
    classname = try_to_import(tag_suffix)
  File "/home/ubgpu/github/hebel/hebel/config.py", line 251, in try_to_import
    exec('import %s' % modulename)
  File "<string>", line 1, in <module>
  File "/home/ubgpu/github/hebel/hebel/layers/__init__.py", line 17, in <module>
    from .dummy_layer import DummyLayer
  File "/home/ubgpu/github/hebel/hebel/layers/dummy_layer.py", line 17, in <module>
    from .hidden_layer import HiddenLayer
  File "/home/ubgpu/github/hebel/hebel/layers/hidden_layer.py", line 25, in <module>
    from ..pycuda_ops import linalg
  File "/home/ubgpu/github/hebel/hebel/pycuda_ops/linalg.py", line 32, in <module>
    from . import cublas
  File "/home/ubgpu/github/hebel/hebel/pycuda_ops/cublas.py", line 47, in <module>
    import cuda
  File "/home/ubgpu/github/hebel/hebel/pycuda_ops/cuda.py", line 36, in <module>
    from cudadrv import *
  File "/home/ubgpu/github/hebel/hebel/pycuda_ops/cudadrv.py", line 233, in <module>
    _libcuda.cuPointerGetAttribute.restype = int
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: cuPointerGetAttribute
ubgpu@ubgpu:~/github/hebel$

**Comment by hannes-brt** [comment]
I'm sorry, but I can't help you with your installation issues. The bug tracker is for bug reports.

**Comment by andyyuan78** [comment]
it is a bug, i under exactly the guide of the document.
